import { notFound } from "next/navigation";
import { getKanjiDetail } from "@/lib/knowledge/service";

export const dynamic = "force-dynamic";

export default async function KanjiPage({ params }: { params: Promise<{ literal: string }> }) {
  const { literal } = await params;
  const kanji = await getKanjiDetail(literal);
  if (!kanji) notFound();

  return (
    <main className="min-h-screen bg-[#f2f4ed] px-5 py-10"><article className="mx-auto max-w-4xl rounded-[1.5rem] border border-[#dce3d8] bg-[#fbfcf7] p-7 shadow-[0_16px_40px_rgba(40,59,43,0.08)]"><a href="/knowledge" className="text-sm font-bold text-[#277a5c] underline">← Knowledge search</a><div className="mt-5 flex flex-wrap items-end gap-6"><div className="grid h-36 w-36 place-items-center rounded-2xl bg-[#edf0e9] font-serif text-8xl text-[#18231d]">{kanji.literal}</div><div><p className="text-xs font-extrabold tracking-[.16em] text-[#277a5c]">KANJI {kanji.jlptLevel ? `· ${kanji.jlptLevel}` : ""}</p><h1 className="mt-1 font-serif text-4xl font-normal text-[#18231d]">{kanji.meanings.map((meaning) => meaning.meaning).join(", ")}</h1><p className="mt-2 text-sm text-[#657166]">{kanji.strokeCount ?? "—"} strokes · Radical {kanji.radical ?? "—"} · Frequency {kanji.frequencyRank ?? "—"}</p></div></div><section className="mt-7 grid gap-5 md:grid-cols-2"><div><h2 className="font-serif text-2xl font-normal text-[#18231d]">Readings</h2><div className="mt-3 space-y-2">{kanji.readings.map((reading) => <p className="rounded-xl bg-[#edf0e9] px-3 py-2 text-sm text-[#415247]" key={reading.id}><span className="font-bold">{reading.kind}</span> · {reading.reading}</p>)}</div></div><div><h2 className="font-serif text-2xl font-normal text-[#18231d]">Components</h2><div className="mt-3 flex flex-wrap gap-2">{kanji.components.map((component) => <span className="rounded-lg bg-[#edf0e9] px-3 py-2 font-serif text-lg text-[#18231d]" key={component.id}>{component.componentLiteral}</span>)}</div></div></section><section className="mt-7"><h2 className="font-serif text-2xl font-normal text-[#18231d]">Stroke order data</h2><p className="mt-1 text-sm text-[#657166]">{kanji.strokes.length > 0 ? `${kanji.strokes.length} KanjiVG paths are available for animation-capable clients.` : "No KanjiVG source paths have been imported for this character."}</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{kanji.strokes.map((stroke) => <details className="rounded-xl border border-[#dce3d8] p-3" key={stroke.id}><summary className="cursor-pointer text-sm font-bold text-[#415247]">Stroke {stroke.strokeNumber}</summary><code className="mt-3 block max-h-28 overflow-auto whitespace-pre-wrap break-all text-xs text-[#657166]">{stroke.svgPath}</code></details>)}</div></section><p className="mt-7 text-xs text-[#748076]">Unicode U+{kanji.unicodeCodepoint} · Source record hash {kanji.sourceHash}</p></article></main>
  );
}
