import type { RawSentenceSourceRecord } from "./types";

/**
 * Curated 25-record controlled pilot fixture from Tatoeba corpus.
 * Contains Japanese sentences with English translations, kana readings,
 * natural cross-entity links to dictionary entries, kanji, and grammar patterns.
 */
export const TATOEBA_PILOT_FIXTURE: RawSentenceSourceRecord[] = [
  {
    tatoebaId: "1001",
    japanese: "冷たい水を一杯飲みました。",
    reading: "つめたいみずをいっぱいのみました。",
    english: "I drank a glass of cold water.",
    jlptLevel: "N5",
    tags: ["daily-life", "beverage"],
  },
  {
    tatoebaId: "1002",
    japanese: "学生たちは教室で日本語の本を読んでいます。",
    reading: "がくせいたちはきょうしつでにほんごのほんをよんでいます。",
    english: "The students are reading Japanese books in the classroom.",
    jlptLevel: "N5",
    tags: ["school", "reading"],
  },
  {
    tatoebaId: "1003",
    japanese: "朝ご飯を食べてから、学校へ行きます。",
    reading: "あさごはんをたべてから、がっこうへいきます。",
    english: "After eating breakfast, I go to school.",
    jlptLevel: "N5",
    tags: ["routine", "movement"],
  },
  {
    tatoebaId: "1004",
    japanese: "先生は親切に文法を教えてくれました。",
    reading: "せんせいはしんせつにぶんぽうをおしえてくれました。",
    english: "The teacher kindly taught us grammar.",
    jlptLevel: "N5",
    tags: ["school", "people"],
  },
  {
    tatoebaId: "1005",
    japanese: "この山は春になると桜の花がきれいです。",
    reading: "このやまははるになるとさくらのはながきれいです。",
    english: "When spring arrives, cherry blossoms on this mountain are beautiful.",
    jlptLevel: "N5",
    tags: ["nature", "season"],
  },
  {
    tatoebaId: "1006",
    japanese: "川の近くで友達と楽しく話しました。",
    reading: "かわのちかくでともだちとたのしくはなしました。",
    english: "I had an enjoyable talk with my friend near the river.",
    jlptLevel: "N5",
    tags: ["friendship", "leisure"],
  },
  {
    tatoebaId: "1007",
    japanese: "駅まで電車で行って、それから歩きました。",
    reading: "えきまででんしゃでいって、それからあるきました。",
    english: "I went to the station by train and then walked.",
    jlptLevel: "N5",
    tags: ["transport", "travel"],
  },
  {
    tatoebaId: "1008",
    japanese: "父は新しい車を買いたいと言っています。",
    reading: "ちはあたらしいくるまをかいたいといっています。",
    english: "My father says he wants to buy a new car.",
    jlptLevel: "N5",
    tags: ["family", "shopping"],
  },
  {
    tatoebaId: "1009",
    japanese: "時間がありませんから、急いで駅へ行きましょう。",
    reading: "じかんがありませんから、いそいでえきへいきましょう。",
    english: "Since there is no time, let's hurry to the station.",
    jlptLevel: "N5",
    tags: ["time", "movement"],
  },
  {
    tatoebaId: "1010",
    japanese: "毎日日本語の漢字を練習しています。",
    reading: "まいにちにほんごのかんじをれんしゅうしています。",
    english: "I practice Japanese kanji every day.",
    jlptLevel: "N5",
    tags: ["study", "language"],
  },
  {
    tatoebaId: "1011",
    japanese: "机の上に手紙と本が置いてあります。",
    reading: "つくえのうえにてがみとほんがおいてあります。",
    english: "There are letters and books on the desk.",
    jlptLevel: "N5",
    tags: ["objects", "furniture"],
  },
  {
    tatoebaId: "1012",
    japanese: "部屋の窓を開けると、心地よい風が入ってきた。",
    reading: "へやのまどをあけると、ここちよいかぜがはいってきた。",
    english: "When I opened the room's window, a pleasant breeze came in.",
    jlptLevel: "N4",
    tags: ["home", "weather"],
  },
  {
    tatoebaId: "1013",
    japanese: "明日は雨が降るかもしれませんから、傘を持って行きなさい。",
    reading: "あしたはあめがふるかもしれませんから、かさをもってゆきなさい。",
    english: "It might rain tomorrow, so take an umbrella.",
    jlptLevel: "N5",
    tags: ["weather", "advice"],
  },
  {
    tatoebaId: "1014",
    japanese: "青い空に白い雲がゆっくり浮かんでいます。",
    reading: "あおいそらにしろいくもがゆっくりうかんでいます。",
    english: "White clouds are floating slowly across the blue sky.",
    jlptLevel: "N5",
    tags: ["nature", "weather"],
  },
  {
    tatoebaId: "1015",
    japanese: "音楽を聞きながら仕事をするのが好きです。",
    reading: "おんがくをききながらしごとをするのがすきです。",
    english: "I like working while listening to music.",
    jlptLevel: "N4",
    tags: ["work", "music"],
  },
  {
    tatoebaId: "1016",
    japanese: "電車より飛行機のほうがずっと速いです。",
    reading: "でんしゃよりひこうきのほうがずっとはやいです。",
    english: "An airplane is much faster than a train.",
    jlptLevel: "N5",
    tags: ["transport", "comparison"],
  },
  {
    tatoebaId: "1017",
    japanese: "健康のために毎日の食事に気をつけています。",
    reading: "けんこうのためにまいにちのしょくじにきをつけています。",
    english: "I am careful about my daily meals for the sake of good health.",
    jlptLevel: "N4",
    tags: ["health", "food"],
  },
  {
    tatoebaId: "1018",
    japanese: "日本へ行ったことがありますか。",
    reading: "にほんへいったことがありますか。",
    english: "Have you ever been to Japan?",
    jlptLevel: "N4",
    tags: ["travel", "experience"],
  },
  {
    tatoebaId: "1019",
    japanese: "試験のことは心配しないでください。",
    reading: "しけんのことはしんぱいしないでください。",
    english: "Please do not worry about the exam.",
    jlptLevel: "N4",
    tags: ["emotion", "encouragement"],
  },
  {
    tatoebaId: "1020",
    japanese: "図書館では大きな声で話さないでください。",
    reading: "としょかんではおおきなこえではなさないでください。",
    english: "Please do not speak in a loud voice in the library.",
    jlptLevel: "N5",
    tags: ["public", "rules"],
  },
  {
    tatoebaId: "1021",
    japanese: "明日までにこの報告書を書かなければならない。",
    reading: "あしたまでにこのほうこくしょをかかなければならない。",
    english: "I must write this report by tomorrow.",
    jlptLevel: "N4",
    tags: ["work", "obligation"],
  },
  {
    tatoebaId: "1022",
    japanese: "彼は漢字を千字以上書くことができる。",
    reading: "かれはかんじをせんじいじょうかくことができる。",
    english: "He is able to write more than one thousand kanji characters.",
    jlptLevel: "N4",
    tags: ["skill", "study"],
  },
  {
    tatoebaId: "1023",
    japanese: "夏休みには海の近くの町へ行く予定です。",
    reading: "なつやすみにはうみのちかくのまちへいくよていです。",
    english: "I plan to go to a seaside town during summer vacation.",
    jlptLevel: "N5",
    tags: ["vacation", "summer"],
  },
  {
    tatoebaId: "1024",
    japanese: "秋になると木の葉が赤や黄色に変わります。",
    reading: "あきになるときのはがあかやきいろにかわります。",
    english: "When autumn arrives, tree leaves turn red and yellow.",
    jlptLevel: "N5",
    tags: ["season", "nature"],
  },
  {
    tatoebaId: "1025",
    japanese: "冬の朝はとても寒くて、布団から出るのが大変です。",
    reading: "ふゆのあさはとてもさむくて、ふとんからでるのがたいへんです。",
    english: "Winter mornings are very cold, and it is hard to get out of the futon.",
    jlptLevel: "N5",
    tags: ["season", "winter"],
  },
];
