export type GrammarSeed = {
  slug: string;
  title: string;
  structure: string;
  level: string;
  explanation: string;
  difficulty: number;
  formation: string;
  nuance: string;
  examples: { ja: string; en: string }[];
  requires?: string[];
  builder?: { prompt: string; tiles: string[]; answer: string };
};

export const GRAMMAR_POINTS: GrammarSeed[] = [
  {
    slug: "desu",
    title: "です",
    structure: "N + です",
    level: "N5",
    explanation: "Polite copula that states identity or a quality.",
    difficulty: 1,
    formation: "Attach です directly to a noun or na-adjective.",
    nuance: "Neutral politeness. Drop to だ in casual speech.",
    examples: [
      { ja: "わたしは学生です。", en: "I am a student." },
      { ja: "これは本です。", en: "This is a book." },
    ],
    builder: { prompt: "I am a student", tiles: ["わたし", "は", "学生", "です"], answer: "わたしは学生です" },
  },
  {
    slug: "masu",
    title: "ます",
    structure: "V-stem + ます",
    level: "N5",
    explanation: "Polite non-past verb ending.",
    difficulty: 1,
    formation: "Take the i-stem of the verb and add ます.",
    nuance: "Default register with strangers and in class.",
    examples: [
      { ja: "水を飲みます。", en: "I drink water." },
      { ja: "毎日勉強します。", en: "I study every day." },
    ],
    requires: ["desu"],
    builder: { prompt: "I drink water", tiles: ["水", "を", "飲みます"], answer: "水を飲みます" },
  },
  {
    slug: "wa",
    title: "は",
    structure: "N + は",
    level: "N5",
    explanation: "Marks the topic — what the sentence is about.",
    difficulty: 1,
    formation: "Place は after the topic noun. Written は, read wa.",
    nuance: "Contrasts with が, which introduces new information.",
    examples: [{ ja: "駅はどこですか。", en: "Where is the station?" }],
    builder: { prompt: "Where is the station?", tiles: ["駅", "は", "どこ", "ですか"], answer: "駅はどこですか" },
  },
  {
    slug: "ga",
    title: "が",
    structure: "N + が",
    level: "N5",
    explanation: "Subject particle. Introduces new or emphasized information.",
    difficulty: 2,
    formation: "Place が after the grammatical subject.",
    nuance: "Answers 'who/what did it', unlike topic は.",
    examples: [{ ja: "猫がいます。", en: "There is a cat." }],
    requires: ["wa"],
  },
  {
    slug: "wo",
    title: "を",
    structure: "N + を + V",
    level: "N5",
    explanation: "Marks the direct object of a transitive verb.",
    difficulty: 1,
    formation: "Noun + を + verb.",
    nuance: "Also marks the path travelled with motion verbs.",
    examples: [{ ja: "本を読みます。", en: "I read a book." }],
    requires: ["masu"],
    builder: { prompt: "I read a book", tiles: ["本", "を", "読みます"], answer: "本を読みます" },
  },
  {
    slug: "ni",
    title: "に",
    structure: "N + に",
    level: "N5",
    explanation: "Point in time, destination, or indirect object.",
    difficulty: 2,
    formation: "Noun + に before a verb of motion or existence.",
    nuance: "に is the arrival point; で is where an action happens.",
    examples: [{ ja: "七時に起きます。", en: "I get up at seven." }],
    requires: ["masu"],
  },
  {
    slug: "de",
    title: "で",
    structure: "N + で",
    level: "N5",
    explanation: "Location of an action, or the means used.",
    difficulty: 2,
    formation: "Noun + で + action verb.",
    nuance: "Contrast with に for existence.",
    examples: [{ ja: "図書館で勉強します。", en: "I study at the library." }],
    requires: ["ni"],
  },
  {
    slug: "ka",
    title: "か",
    structure: "Sentence + か",
    level: "N5",
    explanation: "Turns a statement into a question.",
    difficulty: 1,
    formation: "Append か to the polite form.",
    nuance: "No question mark needed in formal writing.",
    examples: [{ ja: "学生ですか。", en: "Are you a student?" }],
    requires: ["desu"],
  },
  {
    slug: "no",
    title: "の",
    structure: "N1 + の + N2",
    level: "N5",
    explanation: "Links nouns: possession, origin, or description.",
    difficulty: 1,
    formation: "Owner + の + owned.",
    nuance: "Can nominalize verbs in later levels.",
    examples: [{ ja: "日本の車です。", en: "It is a Japanese car." }],
  },
  {
    slug: "tai",
    title: "たい",
    structure: "V-stem + たい",
    level: "N4",
    explanation: "Expresses the speaker's desire to do something.",
    difficulty: 3,
    formation: "Verb i-stem + たい. Conjugates like an i-adjective.",
    nuance: "Use たがる for third parties.",
    examples: [{ ja: "寿司が食べたいです。", en: "I want to eat sushi." }],
    requires: ["masu", "wo"],
    builder: { prompt: "I want to eat sushi", tiles: ["寿司", "が", "食べたい", "です"], answer: "寿司が食べたいです" },
  },
  {
    slug: "teiru",
    title: "ている",
    structure: "V-て + いる",
    level: "N4",
    explanation: "Progressive action or a resulting state.",
    difficulty: 3,
    formation: "Te-form + いる (polite: います).",
    nuance: "With 知る it means 'know', not 'is knowing'.",
    examples: [{ ja: "今、勉強しています。", en: "I am studying now." }],
    requires: ["masu"],
  },
  {
    slug: "te-kudasai",
    title: "てください",
    structure: "V-て + ください",
    level: "N5",
    explanation: "Polite request.",
    difficulty: 2,
    formation: "Te-form + ください.",
    nuance: "Softer with すみませんが in front.",
    examples: [{ ja: "もう一度言ってください。", en: "Please say it once more." }],
    requires: ["masu"],
  },
  {
    slug: "nakereba",
    title: "なければならない",
    structure: "V-ない stem + なければならない",
    level: "N4",
    explanation: "Obligation: must do.",
    difficulty: 4,
    formation: "Drop ない, add ければならない.",
    nuance: "Casual contraction: なきゃ.",
    examples: [{ ja: "早く帰らなければなりません。", en: "I must go home early." }],
    requires: ["teiru"],
  },
  {
    slug: "kara",
    title: "から",
    structure: "Reason + から",
    level: "N5",
    explanation: "Gives a reason or cause.",
    difficulty: 2,
    formation: "Plain or polite clause + から.",
    nuance: "ので is softer and more formal.",
    examples: [{ ja: "寒いから、窓を閉めます。", en: "Because it is cold, I close the window." }],
    requires: ["desu"],
  },
  {
    slug: "node",
    title: "ので",
    structure: "Reason + ので",
    level: "N4",
    explanation: "Soft causal connector.",
    difficulty: 3,
    formation: "Plain form + ので (な after na-adjectives and nouns).",
    nuance: "Less blunt than から in requests.",
    examples: [{ ja: "電車が遅れたので、遅刻しました。", en: "I was late because the train was delayed." }],
    requires: ["kara"],
  },
  {
    slug: "ba",
    title: "ば",
    structure: "V-conditional + ば",
    level: "N4",
    explanation: "Conditional: if this happens, then…",
    difficulty: 4,
    formation: "Change final -u to -eba.",
    nuance: "General or hypothetical conditions.",
    examples: [{ ja: "行けば分かります。", en: "If you go, you'll understand." }],
    requires: ["nakereba"],
  },
  {
    slug: "tara",
    title: "たら",
    structure: "V-た + ら",
    level: "N4",
    explanation: "Conditional / after doing.",
    difficulty: 4,
    formation: "Past plain form + ら.",
    nuance: "Most flexible conditional in speech.",
    examples: [{ ja: "駅に着いたら電話します。", en: "I'll call when I arrive at the station." }],
    requires: ["ba"],
  },
  {
    slug: "passive",
    title: "受身 (られる)",
    structure: "V-passive",
    level: "N4",
    explanation: "Passive voice; often suffering passive.",
    difficulty: 5,
    formation: "Godan: -a + れる. Ichidan: stem + られる.",
    nuance: "Also used for neutral politeness.",
    examples: [{ ja: "先生に褒められました。", en: "I was praised by the teacher." }],
    requires: ["teiru"],
  },
  {
    slug: "causative",
    title: "使役 (させる)",
    structure: "V-causative",
    level: "N3",
    explanation: "Make or let someone do something.",
    difficulty: 6,
    formation: "Godan: -a + せる. Ichidan: stem + させる.",
    nuance: "Combine with てもらう for polite permission.",
    examples: [{ ja: "子供に野菜を食べさせます。", en: "I make the child eat vegetables." }],
    requires: ["passive"],
  },
  {
    slug: "keigo-sonkeigo",
    title: "尊敬語",
    structure: "お + V-stem + になる",
    level: "N3",
    explanation: "Honorific language elevating the listener.",
    difficulty: 7,
    formation: "お + verb stem + になる, or special verbs.",
    nuance: "Never apply to yourself.",
    examples: [{ ja: "先生がお話しになります。", en: "The teacher will speak." }],
    requires: ["causative"],
  },
  {
    slug: "keigo-kenjougo",
    title: "謙譲語",
    structure: "お + V-stem + する",
    level: "N3",
    explanation: "Humble language lowering yourself.",
    difficulty: 7,
    formation: "お + verb stem + する / いたす.",
    nuance: "Pairs with 尊敬語 in business Japanese.",
    examples: [{ ja: "お荷物をお持ちします。", en: "I will carry your luggage." }],
    requires: ["keigo-sonkeigo"],
  },
  {
    slug: "you-ni-naru",
    title: "ようになる",
    structure: "V-plain + ようになる",
    level: "N3",
    explanation: "Change over time: come to do something.",
    difficulty: 6,
    formation: "Dictionary or potential form + ようになる.",
    nuance: "Emphasises gradual change.",
    examples: [{ ja: "漢字が読めるようになりました。", en: "I became able to read kanji." }],
    requires: ["tara"],
  },
  {
    slug: "hazu",
    title: "はず",
    structure: "Plain + はずだ",
    level: "N3",
    explanation: "Expectation based on evidence.",
    difficulty: 5,
    formation: "Plain form + はずだ／はずです.",
    nuance: "Stronger than でしょう.",
    examples: [{ ja: "彼は来るはずです。", en: "He is supposed to come." }],
    requires: ["node"],
  },
  {
    slug: "rashii",
    title: "らしい",
    structure: "Plain + らしい",
    level: "N3",
    explanation: "Hearsay or typical-of.",
    difficulty: 5,
    formation: "Plain form + らしい.",
    nuance: "Softer than そうだ hearsay.",
    examples: [{ ja: "明日は雨らしいです。", en: "Apparently it will rain tomorrow." }],
    requires: ["hazu"],
  },
  {
    slug: "temo-ii",
    title: "てもいい",
    structure: "V-て + もいい",
    level: "N5",
    explanation: "Permission: may I / it's fine to.",
    difficulty: 2,
    formation: "Te-form + もいいですか for questions.",
    nuance: "Refuse with てはいけません.",
    examples: [{ ja: "写真を撮ってもいいですか。", en: "May I take a photo?" }],
    requires: ["te-kudasai"],
  },
];

export function generateFiller(count: number, offset = 0): GrammarSeed[] {
  const bases = ["表現", "接続", "助詞", "敬語", "副詞"];
  return Array.from({ length: count }, (_, index) => {
    const n = offset + index + 1;
    const base = bases[n % bases.length];
    return {
      slug: `pattern-${n}`,
      title: `${base}パターン${n}`,
      structure: `X + ${base}${n}`,
      level: ["N5", "N4", "N3", "N2", "N1"][n % 5]!,
      explanation: `Generated scaffold ${n} for the ${base} family. Replace with an editorial explanation in the CMS.`,
      difficulty: (n % 9) + 1,
      formation: `Attach ${base}${n} to the plain form.`,
      nuance: "Draft entry awaiting editorial review.",
      examples: [{ ja: `これは${base}${n}の例です。`, en: `This is example ${n}.` }],
    };
  });
}
