import type { KanjiEntryInput, KanjiRadicalInput } from "./types";

/**
 * 12 Curated Pilot Kanji representing various JLPT levels (N5, N4, N3, N2, N1),
 * stroke counts, semantic/phonetic compositions, multiple on/kun readings, and rich vocabulary.
 *
 * Sources: KANJIDIC2 / KanjiVG / Joyo Kanji Reference Standard.
 */

export const PILOT_RADICALS: KanjiRadicalInput[] = [
  // Additional radicals and primitives needed for the pilot Kanji:
  {
    id: "el-shinnyou",
    character: "⻌",
    altForms: ["辶", "⻍"],
    meaning: "road, walk, movement",
    readingKun: "しんにょう",
    readingOn: null,
    strokeCount: 3,
    kangxiNumber: 162,
    category: "radical",
    typicalRole: "semantic",
    mnemonic: "A road with footsteps moving along it.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
  {
    id: "el-kubi",
    character: "首",
    altForms: [],
    meaning: "neck, head, leader",
    readingKun: "くび",
    readingOn: "シュ",
    strokeCount: 9,
    kangxiNumber: 185,
    category: "primitive",
    typicalRole: "phonetic",
    mnemonic: "A head and neck of a person or leader.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
  {
    id: "el-kin",
    character: "斤",
    altForms: [],
    meaning: "axe",
    readingKun: "おの",
    readingOn: "キン",
    strokeCount: 4,
    kangxiNumber: 69,
    category: "radical",
    typicalRole: "semantic",
    mnemonic: "An axe for cutting wood.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
  {
    id: "el-shita-tongue",
    character: "舌",
    altForms: [],
    meaning: "tongue",
    readingKun: "した",
    readingOn: "ゼツ",
    strokeCount: 6,
    kangxiNumber: 135,
    category: "radical",
    typicalRole: "phonetic",
    mnemonic: "A tongue protruding from a mouth.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
  {
    id: "el-ao",
    character: "青",
    altForms: ["靑"],
    meaning: "blue, green",
    readingKun: "あお",
    readingOn: "セイ",
    strokeCount: 8,
    kangxiNumber: 174,
    category: "primitive",
    typicalRole: "phonetic",
    mnemonic: "Pure clear blue sky over growing vegetation.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
  {
    id: "el-kichi",
    character: "吉",
    altForms: [],
    meaning: "good luck, auspicious",
    readingKun: "よし",
    readingOn: "キチ",
    strokeCount: 6,
    kangxiNumber: 30,
    category: "primitive",
    typicalRole: "structural",
    mnemonic: "Words of wisdom from an elder bringing auspiciousness.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
  {
    id: "el-miru",
    character: "見",
    altForms: [],
    meaning: "see, look",
    readingKun: "み・る",
    readingOn: "ケン",
    strokeCount: 7,
    kangxiNumber: 147,
    category: "primitive",
    typicalRole: "semantic",
    mnemonic: "An eye on human legs looking around.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
  {
    id: "el-kan-inspect",
    character: "監",
    altForms: [],
    meaning: "oversee, inspect",
    readingKun: "かんが・みる",
    readingOn: "カン",
    strokeCount: 15,
    kangxiNumber: 108,
    category: "primitive",
    typicalRole: "structural",
    mnemonic: "Looking into a water basin to inspect oneself or supervise others.",
    sourceRef: "first-party:kanji-corpus:v1",
  },
];

export const PILOT_KANJI_ENTRIES: KanjiEntryInput[] = [
  // 1. 道 (N5, Road / Way)
  {
    id: "kanji-road",
    character: "道",
    meaning: "road, path, way, teachings",
    readingsKun: ["みち", "いう"],
    readingsOn: ["ドウ", "トウ"],
    strokeCount: 12,
    jlptLevel: "N5",
    gradeLevel: 2,
    primaryRadicalId: "el-shinnyou",
    mnemonic: "Walking along the path guided by one's head/vision.",
    vocabulary: [
      { word: "道路", reading: "どうろ", meaning: "road, highway" },
      { word: "茶道", reading: "さどう", meaning: "tea ceremony" },
      { word: "近道", reading: "ちかみち", meaning: "shortcut" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-road",
        elementId: "el-shinnyou",
        role: "semantic",
        position: "enclosure",
        renderedAs: "⻌",
        orderIndex: 2,
      },
      {
        kanjiId: "kanji-road",
        elementId: "el-kubi",
        role: "phonetic",
        position: "inside",
        renderedAs: "首",
        orderIndex: 1,
      },
    ],
  },
  // 2. 新 (N5, New)
  {
    id: "kanji-new",
    character: "新",
    meaning: "new, fresh",
    readingsKun: ["あたら・しい", "あら・た", "にい"],
    readingsOn: ["シン"],
    strokeCount: 13,
    jlptLevel: "N5",
    gradeLevel: 2,
    primaryRadicalId: "el-kin",
    mnemonic: "Standing next to a tree with an axe to cut new fresh wood.",
    vocabulary: [
      { word: "新聞", reading: "しんぶん", meaning: "newspaper" },
      { word: "新年", reading: "しんねん", meaning: "New Year" },
      { word: "新しい", reading: "あたらしい", meaning: "new" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-new",
        elementId: "el-tatsu",
        role: "semantic",
        position: "left",
        renderedAs: "立",
        orderIndex: 1,
      },
      {
        kanjiId: "kanji-new",
        elementId: "el-ki",
        role: "semantic",
        position: "left",
        renderedAs: "木",
        orderIndex: 2,
      },
      {
        kanjiId: "kanji-new",
        elementId: "el-kin",
        role: "semantic",
        position: "right",
        renderedAs: "斤",
        orderIndex: 3,
      },
    ],
  },
  // 3. 話 (N5, Talk / Speak)
  {
    id: "kanji-talk",
    character: "話",
    meaning: "talk, speech, conversation, story",
    readingsKun: ["はな・す", "はなし"],
    readingsOn: ["ワ"],
    strokeCount: 13,
    jlptLevel: "N5",
    gradeLevel: 2,
    primaryRadicalId: "el-gen",
    mnemonic: "Words spoken using the tongue.",
    vocabulary: [
      { word: "電話", reading: "でんわ", meaning: "telephone" },
      { word: "会話", reading: "かいわ", meaning: "conversation" },
      { word: "話す", reading: "はなす", meaning: "to speak" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-talk",
        elementId: "el-gen",
        role: "semantic",
        position: "left",
        renderedAs: "言",
        orderIndex: 1,
      },
      {
        kanjiId: "kanji-talk",
        elementId: "el-shita-tongue",
        role: "phonetic",
        position: "right",
        renderedAs: "舌",
        orderIndex: 2,
      },
    ],
  },
  // 4. 水 (N5, Water - Enriched)
  {
    id: "kj-mizu",
    character: "水",
    meaning: "water",
    readingsKun: ["みず", "みず-"],
    readingsOn: ["スイ"],
    strokeCount: 4,
    jlptLevel: "N5",
    gradeLevel: 1,
    primaryRadicalId: "el-mizu",
    mnemonic: "Water swirling down a central stream with droplets on each side.",
    vocabulary: [
      { word: "水", reading: "みず", meaning: "water" },
      { word: "水曜日", reading: "すいようび", meaning: "Wednesday" },
      { word: "水泳", reading: "すいえい", meaning: "swimming" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kj-mizu",
        elementId: "el-mizu",
        role: "semantic",
        position: "integrated",
        renderedAs: "水",
        orderIndex: 1,
      },
    ],
  },
  // 5. 火 (N5, Fire - Enriched)
  {
    id: "kj-hi",
    character: "火",
    meaning: "fire",
    readingsKun: ["ひ", "-び", "ほ-"],
    readingsOn: ["カ"],
    strokeCount: 4,
    jlptLevel: "N5",
    gradeLevel: 1,
    primaryRadicalId: "el-hi",
    mnemonic: "Flames flickering upward from embers.",
    vocabulary: [
      { word: "火", reading: "ひ", meaning: "fire" },
      { word: "火曜日", reading: "かようび", meaning: "Tuesday" },
      { word: "火事", reading: "かじ", meaning: "fire, conflagration" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kj-hi",
        elementId: "el-hi",
        role: "semantic",
        position: "integrated",
        renderedAs: "火",
        orderIndex: 1,
      },
    ],
  },
  // 6. 心 (N4, Heart / Mind)
  {
    id: "kanji-heart",
    character: "心",
    meaning: "heart, mind, spirit",
    readingsKun: ["こころ", "-ごころ"],
    readingsOn: ["シン"],
    strokeCount: 4,
    jlptLevel: "N4",
    gradeLevel: 2,
    primaryRadicalId: "el-kokoro",
    mnemonic: "An anatomical rendering of the heart chambers pumping blood.",
    vocabulary: [
      { word: "安心", reading: "あんしん", meaning: "peace of mind, relief" },
      { word: "中心", reading: "ちゅうしん", meaning: "center, focus" },
      { word: "心臓", reading: "しんぞう", meaning: "heart (organ)" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-heart",
        elementId: "el-kokoro",
        role: "semantic",
        position: "integrated",
        renderedAs: "心",
        orderIndex: 1,
      },
    ],
  },
  // 7. 紙 (N4, Paper)
  {
    id: "kanji-paper",
    character: "紙",
    meaning: "paper",
    readingsKun: ["かみ"],
    readingsOn: ["シ"],
    strokeCount: 10,
    jlptLevel: "N4",
    gradeLevel: 2,
    primaryRadicalId: "el-ito",
    mnemonic: "Fine threads pressed and dried flat into paper.",
    vocabulary: [
      { word: "手紙", reading: "てがみ", meaning: "letter" },
      { word: "折り紙", reading: "おりがみ", meaning: "origami" },
      { word: "用紙", reading: "ようし", meaning: "blank form, paper sheet" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-paper",
        elementId: "el-ito",
        role: "semantic",
        position: "left",
        renderedAs: "糸",
        orderIndex: 1,
      },
    ],
  },
  // 8. 晴 (N4, Clear weather)
  {
    id: "kanji-clear-weather",
    character: "晴",
    meaning: "clear weather, fair skies",
    readingsKun: ["は・れる", "は・れ", "-ばれ", "は・らす"],
    readingsOn: ["セイ"],
    strokeCount: 12,
    jlptLevel: "N4",
    gradeLevel: 2,
    primaryRadicalId: "el-hi2",
    mnemonic: "The sun brings blue skies and clear weather.",
    vocabulary: [
      { word: "晴れ", reading: "はれ", meaning: "clear weather" },
      { word: "晴天", reading: "せいてん", meaning: "fine clear sky" },
      { word: "素晴らしい", reading: "すばらしい", meaning: "wonderful, splendid" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-clear-weather",
        elementId: "el-hi2",
        role: "semantic",
        position: "left",
        renderedAs: "日",
        orderIndex: 1,
      },
      {
        kanjiId: "kanji-clear-weather",
        elementId: "el-ao",
        role: "phonetic",
        position: "right",
        renderedAs: "青",
        orderIndex: 2,
      },
    ],
  },
  // 9. 結 (N3, Tie / Bind / Conclude)
  {
    id: "kanji-bind",
    character: "結",
    meaning: "tie, bind, contract, join",
    readingsKun: ["むす・ぶ", "ゆ・う", "ゆ・わえる"],
    readingsOn: ["ケツ", "ケチ"],
    strokeCount: 12,
    jlptLevel: "N3",
    gradeLevel: 4,
    primaryRadicalId: "el-ito",
    mnemonic: "Threads tied together to bind firmly.",
    vocabulary: [
      { word: "結婚", reading: "けっこん", meaning: "marriage" },
      { word: "結果", reading: "けっか", meaning: "result" },
      { word: "結論", reading: "けつろん", meaning: "conclusion" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-bind",
        elementId: "el-ito",
        role: "semantic",
        position: "left",
        renderedAs: "糸",
        orderIndex: 1,
      },
      {
        kanjiId: "kanji-bind",
        elementId: "el-kichi",
        role: "structural",
        position: "right",
        renderedAs: "吉",
        orderIndex: 2,
      },
    ],
  },
  // 10. 念 (N3, Thought / Desire / Attention)
  {
    id: "kanji-thought",
    character: "念",
    meaning: "thought, sentiment, desire, attention",
    readingsKun: [],
    readingsOn: ["ネン"],
    strokeCount: 8,
    jlptLevel: "N3",
    gradeLevel: 4,
    primaryRadicalId: "el-kokoro",
    mnemonic: "What is currently residing in your heart/mind.",
    vocabulary: [
      { word: "残念", reading: "ざんねん", meaning: "regrettable, unfortunate" },
      { word: "記念", reading: "きねん", meaning: "commemoration, memory" },
      { word: "専念", reading: "せんねん", meaning: "devoting oneself to" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-thought",
        elementId: "el-kokoro",
        role: "semantic",
        position: "bottom",
        renderedAs: "心",
        orderIndex: 2,
      },
    ],
  },
  // 11. 観 (N2, Look / View / Observe)
  {
    id: "kanji-observe",
    character: "観",
    meaning: "look, view, observe, sight",
    readingsKun: ["み・る", "しめ・す"],
    readingsOn: ["カン"],
    strokeCount: 18,
    jlptLevel: "N2",
    gradeLevel: 4,
    primaryRadicalId: "el-me",
    mnemonic: "Watching a perched bird with sharp observant eyes.",
    vocabulary: [
      { word: "観光", reading: "かんこう", meaning: "sightseeing, tourism" },
      { word: "観察", reading: "かんさつ", meaning: "observation, inspection" },
      { word: "観点", reading: "かんてん", meaning: "point of view" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-observe",
        elementId: "el-miru",
        role: "semantic",
        position: "right",
        renderedAs: "見",
        orderIndex: 2,
      },
    ],
  },
  // 12. 鑑 (N1, Specimen / Mirror / Model / Discern)
  {
    id: "kanji-discern",
    character: "鑑",
    meaning: "specimen, take warning from, mirror, inspect, judge",
    readingsKun: ["かんが・みる", "かがみ"],
    readingsOn: ["カン"],
    strokeCount: 23,
    jlptLevel: "N1",
    gradeLevel: 8,
    primaryRadicalId: "el-kane",
    mnemonic: "A bronze metal mirror used to inspect and judge truth.",
    vocabulary: [
      { word: "鑑賞", reading: "かんしょう", meaning: "art appreciation" },
      { word: "鑑定", reading: "かんてい", meaning: "expert appraisal, judgment" },
      { word: "図鑑", reading: "ずかん", meaning: "illustrated field guide" },
    ],
    sourceRef: "first-party:kanji-corpus:v1",
    composition: [
      {
        kanjiId: "kanji-discern",
        elementId: "el-kane",
        role: "semantic",
        position: "left",
        renderedAs: "金",
        orderIndex: 1,
      },
      {
        kanjiId: "kanji-discern",
        elementId: "el-kan-inspect",
        role: "structural",
        position: "right",
        renderedAs: "監",
        orderIndex: 2,
      },
    ],
  },
];
