export const LEXEMES = [
  { ext: "1000000", lemma: "食べる", reading: "たべる", pos: "verb", jlpt: "N5", glosses: ["to eat"], pitch: 2, freq: 120, tags: ["action", "food"] },
  { ext: "1000001", lemma: "飲む", reading: "のむ", pos: "verb", jlpt: "N5", glosses: ["to drink"], pitch: 1, freq: 180, tags: ["action", "food"] },
  { ext: "1000002", lemma: "行く", reading: "いく", pos: "verb", jlpt: "N5", glosses: ["to go"], pitch: 0, freq: 40, tags: ["action", "motion"] },
  { ext: "1000003", lemma: "来る", reading: "くる", pos: "verb", jlpt: "N5", glosses: ["to come"], pitch: 1, freq: 80, tags: ["action", "motion"] },
  { ext: "1000004", lemma: "見る", reading: "みる", pos: "verb", jlpt: "N5", glosses: ["to see", "to watch"], pitch: 1, freq: 90, tags: ["action"] },
  { ext: "1000005", lemma: "する", reading: "する", pos: "verb", jlpt: "N5", glosses: ["to do"], pitch: 0, freq: 10, tags: ["action"] },
  { ext: "1000006", lemma: "水", reading: "みず", pos: "noun", jlpt: "N5", glosses: ["water"], pitch: 0, freq: 200, tags: ["nature"] },
  { ext: "1000007", lemma: "本", reading: "ほん", pos: "noun", jlpt: "N5", glosses: ["book"], pitch: 1, freq: 150, tags: ["object"] },
  { ext: "1000008", lemma: "人", reading: "ひと", pos: "noun", jlpt: "N5", glosses: ["person"], pitch: 0, freq: 30, tags: ["human"] },
  { ext: "1000009", lemma: "日本", reading: "にほん", pos: "noun", jlpt: "N5", glosses: ["Japan"], pitch: 2, freq: 70, tags: ["place"] },
  { ext: "1000010", lemma: "先生", reading: "せんせい", pos: "noun", jlpt: "N5", glosses: ["teacher"], pitch: 3, freq: 260, tags: ["human"] },
  { ext: "1000011", lemma: "学生", reading: "がくせい", pos: "noun", jlpt: "N5", glosses: ["student"], pitch: 3, freq: 310, tags: ["human"] },
  { ext: "1000012", lemma: "学校", reading: "がっこう", pos: "noun", jlpt: "N5", glosses: ["school"], pitch: 0, freq: 220, tags: ["place"] },
  { ext: "1000013", lemma: "駅", reading: "えき", pos: "noun", jlpt: "N5", glosses: ["station"], pitch: 1, freq: 240, tags: ["place", "travel"] },
  { ext: "1000014", lemma: "電車", reading: "でんしゃ", pos: "noun", jlpt: "N5", glosses: ["train"], pitch: 0, freq: 280, tags: ["travel"] },
  { ext: "1000015", lemma: "今日", reading: "きょう", pos: "noun", jlpt: "N5", glosses: ["today"], pitch: 1, freq: 110, tags: ["time"] },
  { ext: "1000016", lemma: "明日", reading: "あした", pos: "noun", jlpt: "N5", glosses: ["tomorrow"], pitch: 3, freq: 190, tags: ["time"] },
  { ext: "1000017", lemma: "昨日", reading: "きのう", pos: "noun", jlpt: "N5", glosses: ["yesterday"], pitch: 2, freq: 210, tags: ["time"] },
  { ext: "1000018", lemma: "大きい", reading: "おおきい", pos: "adj", jlpt: "N5", glosses: ["big"], pitch: 3, freq: 170, tags: ["quality"] },
  { ext: "1000019", lemma: "小さい", reading: "ちいさい", pos: "adj", jlpt: "N5", glosses: ["small"], pitch: 3, freq: 230, tags: ["quality"] },
  { ext: "1000020", lemma: "新しい", reading: "あたらしい", pos: "adj", jlpt: "N5", glosses: ["new"], pitch: 4, freq: 250, tags: ["quality"] },
  { ext: "1000021", lemma: "古い", reading: "ふるい", pos: "adj", jlpt: "N5", glosses: ["old"], pitch: 2, freq: 300, tags: ["quality"] },
  { ext: "1000022", lemma: "高い", reading: "たかい", pos: "adj", jlpt: "N5", glosses: ["expensive", "tall"], pitch: 2, freq: 160, tags: ["quality"] },
  { ext: "1000023", lemma: "安い", reading: "やすい", pos: "adj", jlpt: "N5", glosses: ["cheap"], pitch: 2, freq: 270, tags: ["quality"] },
  { ext: "1000024", lemma: "美味しい", reading: "おいしい", pos: "adj", jlpt: "N5", glosses: ["delicious"], pitch: 0, freq: 290, tags: ["food"] },
  { ext: "1000025", lemma: "ありがとう", reading: "ありがとう", pos: "int", jlpt: "N5", glosses: ["thank you"], pitch: 2, freq: 50, tags: ["phrase"] },
  { ext: "1000026", lemma: "すみません", reading: "すみません", pos: "int", jlpt: "N5", glosses: ["excuse me", "sorry"], pitch: 3, freq: 60, tags: ["phrase"] },
  { ext: "1000027", lemma: "こんにちは", reading: "こんにちは", pos: "int", jlpt: "N5", glosses: ["hello", "good afternoon"], pitch: 4, freq: 55, tags: ["phrase"] },
  { ext: "1000028", lemma: "猫", reading: "ねこ", pos: "noun", jlpt: "N5", glosses: ["cat"], pitch: 1, freq: 400, tags: ["nature"] },
  { ext: "1000029", lemma: "犬", reading: "いぬ", pos: "noun", jlpt: "N5", glosses: ["dog"], pitch: 2, freq: 390, tags: ["nature"] },
  { ext: "1000030", lemma: "山", reading: "やま", pos: "noun", jlpt: "N5", glosses: ["mountain"], pitch: 2, freq: 330, tags: ["nature"] },
  { ext: "1000031", lemma: "川", reading: "かわ", pos: "noun", jlpt: "N5", glosses: ["river"], pitch: 2, freq: 340, tags: ["nature"] },
  { ext: "1000032", lemma: "雨", reading: "あめ", pos: "noun", jlpt: "N5", glosses: ["rain"], pitch: 1, freq: 350, tags: ["nature"] },
  { ext: "1000033", lemma: "車", reading: "くるま", pos: "noun", jlpt: "N5", glosses: ["car"], pitch: 0, freq: 140, tags: ["object"] },
  { ext: "1000034", lemma: "買う", reading: "かう", pos: "verb", jlpt: "N5", glosses: ["to buy"], pitch: 0, freq: 130, tags: ["action"] },
  { ext: "1000035", lemma: "話す", reading: "はなす", pos: "verb", jlpt: "N5", glosses: ["to speak"], pitch: 2, freq: 125, tags: ["action"] },
];

export const KANJI = [
  { ch: "日", strokes: 4, on: ["ニチ", "ジツ"], kun: ["ひ", "か"], meanings: ["day", "sun"], radical: "日", jlpt: "N5", freq: 1, heisig: "day" },
  { ch: "一", strokes: 1, on: ["イチ"], kun: ["ひと"], meanings: ["one"], radical: "一", jlpt: "N5", freq: 2, heisig: "one" },
  { ch: "人", strokes: 2, on: ["ジン", "ニン"], kun: ["ひと"], meanings: ["person"], radical: "人", jlpt: "N5", freq: 5, heisig: "person" },
  { ch: "山", strokes: 3, on: ["サン"], kun: ["やま"], meanings: ["mountain"], radical: "山", jlpt: "N5", freq: 131, heisig: "mountain" },
  { ch: "川", strokes: 3, on: ["セン"], kun: ["かわ"], meanings: ["river"], radical: "川", jlpt: "N5", freq: 181, heisig: "stream" },
  { ch: "水", strokes: 4, on: ["スイ"], kun: ["みず"], meanings: ["water"], radical: "水", jlpt: "N5", freq: 223, heisig: "water" },
  { ch: "火", strokes: 4, on: ["カ"], kun: ["ひ"], meanings: ["fire"], radical: "火", jlpt: "N5", freq: 574, heisig: "fire" },
  { ch: "木", strokes: 4, on: ["モク"], kun: ["き"], meanings: ["tree"], radical: "木", jlpt: "N5", freq: 317, heisig: "tree" },
  { ch: "金", strokes: 8, on: ["キン"], kun: ["かね"], meanings: ["gold", "money"], radical: "金", jlpt: "N5", freq: 53, heisig: "gold" },
  { ch: "土", strokes: 3, on: ["ド"], kun: ["つち"], meanings: ["soil"], radical: "土", jlpt: "N5", freq: 307, heisig: "soil" },
  { ch: "大", strokes: 3, on: ["ダイ"], kun: ["おお"], meanings: ["large"], radical: "大", jlpt: "N5", freq: 7, heisig: "large" },
  { ch: "小", strokes: 3, on: ["ショウ"], kun: ["ちい", "こ"], meanings: ["small"], radical: "小", jlpt: "N5", freq: 114, heisig: "little" },
  { ch: "中", strokes: 4, on: ["チュウ"], kun: ["なか"], meanings: ["middle"], radical: "丨", jlpt: "N5", freq: 11, heisig: "in" },
  { ch: "上", strokes: 3, on: ["ジョウ"], kun: ["うえ"], meanings: ["up"], radical: "一", jlpt: "N5", freq: 35, heisig: "above" },
  { ch: "下", strokes: 3, on: ["カ", "ゲ"], kun: ["した"], meanings: ["down"], radical: "一", jlpt: "N5", freq: 97, heisig: "below" },
  { ch: "月", strokes: 4, on: ["ゲツ", "ガツ"], kun: ["つき"], meanings: ["month", "moon"], radical: "月", jlpt: "N5", freq: 23, heisig: "moon" },
  { ch: "年", strokes: 6, on: ["ネン"], kun: ["とし"], meanings: ["year"], radical: "干", jlpt: "N5", freq: 6, heisig: "year" },
  { ch: "本", strokes: 5, on: ["ホン"], kun: ["もと"], meanings: ["book", "origin"], radical: "木", jlpt: "N5", freq: 10, heisig: "book" },
  { ch: "東", strokes: 8, on: ["トウ"], kun: ["ひがし"], meanings: ["east"], radical: "木", jlpt: "N5", freq: 37, heisig: "east" },
  { ch: "西", strokes: 6, on: ["セイ"], kun: ["にし"], meanings: ["west"], radical: "西", jlpt: "N5", freq: 259, heisig: "west" },
  { ch: "南", strokes: 9, on: ["ナン"], kun: ["みなみ"], meanings: ["south"], radical: "十", jlpt: "N5", freq: 341, heisig: "south" },
  { ch: "北", strokes: 5, on: ["ホク"], kun: ["きた"], meanings: ["north"], radical: "匕", jlpt: "N5", freq: 153, heisig: "north" },
  { ch: "学", strokes: 8, on: ["ガク"], kun: ["まな"], meanings: ["study"], radical: "子", jlpt: "N5", freq: 63, heisig: "study" },
  { ch: "校", strokes: 10, on: ["コウ"], kun: [], meanings: ["school"], radical: "木", jlpt: "N5", freq: 294, heisig: "exam" },
  { ch: "生", strokes: 5, on: ["セイ", "ショウ"], kun: ["い"], meanings: ["life"], radical: "生", jlpt: "N5", freq: 29, heisig: "life" },
  { ch: "先", strokes: 6, on: ["セン"], kun: ["さき"], meanings: ["before", "ahead"], radical: "儿", jlpt: "N5", freq: 173, heisig: "before" },
  { ch: "車", strokes: 7, on: ["シャ"], kun: ["くるま"], meanings: ["car"], radical: "車", jlpt: "N5", freq: 333, heisig: "car" },
  { ch: "電", strokes: 13, on: ["デン"], kun: [], meanings: ["electricity"], radical: "雨", jlpt: "N5", freq: 268, heisig: "electricity" },
  { ch: "語", strokes: 14, on: ["ゴ"], kun: ["かた"], meanings: ["language", "word"], radical: "言", jlpt: "N5", freq: 301, heisig: "word" },
  { ch: "食", strokes: 9, on: ["ショク"], kun: ["た"], meanings: ["eat", "food"], radical: "食", jlpt: "N5", freq: 328, heisig: "eat" },
];

export const SENTENCES = [
  { ext: "t1", ja: "水を飲みます。", en: "I drink water.", level: "N5", lemmas: ["飲む", "水"] },
  { ext: "t2", ja: "本を読みます。", en: "I read a book.", level: "N5", lemmas: ["本"] },
  { ext: "t3", ja: "駅へ行きます。", en: "I go to the station.", level: "N5", lemmas: ["行く", "駅"] },
  { ext: "t4", ja: "今日は学校です。", en: "Today is a school day.", level: "N5", lemmas: ["今日", "学校"] },
  { ext: "t5", ja: "先生は学生です。", en: "The teacher is a student? Wait — no: this is a drill sentence.", level: "N5", lemmas: ["先生", "学生"] },
  { ext: "t6", ja: "日本の山は美しいです。", en: "Japan's mountains are beautiful.", level: "N5", lemmas: ["日本", "山"] },
  { ext: "t7", ja: "電車は高いです。", en: "The train is expensive.", level: "N5", lemmas: ["電車", "高い"] },
  { ext: "t8", ja: "猫が好きです。", en: "I like cats.", level: "N5", lemmas: ["猫"] },
  { ext: "t9", ja: "すみません、駅はどこですか。", en: "Excuse me, where is the station?", level: "N5", lemmas: ["すみません", "駅"] },
  { ext: "t10", ja: "ありがとうございます。", en: "Thank you very much.", level: "N5", lemmas: ["ありがとう"] },
];

export const GRAMMAR = [
  { slug: "desu", title: "です", structure: "N です", level: "N5", explanation: "Polite copula. Marks identity or state." },
  { slug: "masu", title: "ます", structure: "V-ます", level: "N5", explanation: "Polite verb ending." },
  { slug: "wa", title: "は", structure: "N は", level: "N5", explanation: "Topic particle, read wa." },
  { slug: "wo", title: "を", structure: "N を V", level: "N5", explanation: "Object particle." },
  { slug: "ni", title: "に", structure: "N に", level: "N5", explanation: "Time, destination, or indirect object." },
  { slug: "de", title: "で", structure: "N で V", level: "N5", explanation: "Location of action or means." },
  { slug: "ka", title: "か", structure: "…か", level: "N5", explanation: "Question marker." },
  { slug: "no", title: "の", structure: "N の N", level: "N5", explanation: "Possession or noun modification." },
  { slug: "tai", title: "たい", structure: "V-stem たい", level: "N4", explanation: "Desire to do the verb." },
  { slug: "teiru", title: "ている", structure: "V-て いる", level: "N4", explanation: "Progressive or resultant state." },
];

export const IDIOMS = [
  { ja: "猫の手も借りたい", reading: "ねこのてもかりたい", en: "so busy you'd borrow a cat's paw" },
  { ja: "石の上にも三年", reading: "いしのうえにもさんねん", en: "perseverance prevails" },
  { ja: "猿も木から落ちる", reading: "さるもきからおちる", en: "even experts slip" },
  { ja: "花より団子", reading: "はなよりだんご", en: "substance over style" },
  { ja: "十人十色", reading: "じゅうにんといろ", en: "different strokes" },
  { ja: "一期一会", reading: "いちごいちえ", en: "once-in-a-lifetime encounter" },
];

export const COLLOCATIONS = [
  { left: "お茶", right: "を飲む", en: "drink tea" },
  { left: "電車", right: "に乗る", en: "board a train" },
  { left: "宿題", right: "をする", en: "do homework" },
  { left: "写真", right: "を撮る", en: "take a photo" },
  { left: "雨", right: "が降る", en: "rain falls" },
  { left: "本", right: "を読む", en: "read a book" },
  { left: "日本語", right: "を話す", en: "speak Japanese" },
  { left: "切符", right: "を買う", en: "buy a ticket" },
];

export const NAMES = [
  { surface: "東京", reading: "とうきょう", kind: "place", gloss: "Tokyo" },
  { surface: "京都", reading: "きょうと", kind: "place", gloss: "Kyoto" },
  { surface: "山田", reading: "やまだ", kind: "surname", gloss: "Yamada" },
  { surface: "佐藤", reading: "さとう", kind: "surname", gloss: "Sato" },
  { surface: "富士山", reading: "ふじさん", kind: "place", gloss: "Mt. Fuji" },
];
